<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>chain</title>
</head>
<body>
<div>
</div>
</body>
<script src="https://cdn.bootcss.com/axios/0.19.0/axios.js"></script>
<script type="text/javascript">

    /**
     *
     * 请求拦截器: requestInterceptors: [{fulfilled1(){}, rejected1(){}}, {fulfilled2(){}, rejected2(){}}]
     *  - 请求拦截器是向前追加.
     *  - 后添加的先执行.
     * 响应拦截器: responseInterceptors: [{fulfilled11(){}, rejected11(){}}, {fulfilled22(){}, rejected22(){}}]
     *  - 响应拦截器是向后添加.
     *  - 后添加的后执行.
     * 调用链路:
     * chain: [
     *   fulfilled2, rejected2, fulfilled1, rejected1,
     *   dispatchReqeust, undefined,
     *   fulfilled11, rejected11, fulfilled22, rejected22
     * ]
     * promise链回调: config00000000
     *               => (fulfilled2, rejected2) => (fulfilled1, rejected1)   // 请求拦截器处理
     *               => (dispatchReqeust, undefined) // 发请求
     *               => (fulfilled11, rejected11) => (fulfilled22, rejected22) // 响应拦截器处理
     *               => (onResolved, onRejected) // axios发请求回调处理
     */



    //添加请求拦截器
    axios.interceptors.request.use(
        config => {
            console.log('拦截器1')
            return config
        },
        error => {
            console.log('拦截器1失败')
            return Promise.reject(error)
        }
    )

    axios.interceptors.request.use(
        config => {
            console.log('拦截器2')
            return config
        },
        error => {
            console.log('拦截器2失败')
            return Promise.reject(error)
        }
    )

    //响应拦截器
    axios.interceptors.response.use(
        response => {
            console.log('响应拦截器1')
            return response
        },
        function (error){
            console.log('响应拦截器失败1')
            return Promise.reject(error)
        }
    )
    axios.interceptors.response.use(
        response => {
            console.log('响应拦截器2')
            return response
        },
        function (error){
            console.log('响应拦截器失败2')
            return Promise.reject(error)
        }
    )

    axios.get('http://localhost:3000/posts')
        .then(response => {
            console.log('data',response.data)
        })
        .catch(error => {
            console.log('error',error.message)
        })




</script>
</html>
